#import "@preview/touying:0.5.5": *
#import "@preview/clean-math-presentation:0.1.1": *

#show: clean-math-presentation-theme.with(
  config-info(
    title: [Modeling Project: 3D Reconstruction of Femurs],
    authors: (
      (name: "Boyer Timothé"),
      (name: "Hacini Malik"),
      (name: "Lainé Martin"),
      (name: "Mouret Basile"),
    ),
    date: datetime(year: 2026, month: 01, day:23),
  ),
  config-common(
    slide-level: 3,
    //handout: true,
    //show-notes-on-second-screen: right,
  ),
  progress-bar: true,
)

#title-slide(
  // On met tout dans logo1 avec une grille
  logo1: block(width: 50%)[
    #grid(
      columns: (auto, 1fr, auto), // Gauche - Espace élastique - Droite
      align: horizon,             // Aligne verticalement les images
      image("../assets/im2ag.png", height: 2.5cm),
      [],                         // Case vide qui pousse les images aux bords
      image("../assets/ensimag.png", height: 2.5cm)
    )
  ],
  logo2: none // On s'assure que le 2ème est vide
)
== Outline <touying:hidden>

//#components.adaptive-columns(outline(title: none))

= Introduction

== Context
#slide(title: "Context")[
  - Clustering
  - Shape analysis
  - ... Malik TODO
]

== Data description
#slide(title: "Data description")[
  - use the `visuFemur.py` to show some femur meshes: the femur, the grid (triangle mesh), ... (there is different parameters in the script to show or hide some elements)
  - how we obtained the data ?
]

== First approach : Linear PCA
#slide(title: "First approach : Linear PCA")[
 TODO
]

== Description and goals of the project
#slide(title: "Description and goals of the project")[
  - RDN for the non-linearity: from 54873 to 10 neurons to 54873 --> why 10 ?
  - Implement it from scratch in C++
]

= Linear algebra implementation

#slide(title: "Linear algebra implementation")[
  == Custom library design
  - Built on top of *Eigen* for efficient internal storage
  - Template-based classes: `Vector<T>`, `Matrix2D<T>`, `Matrix2DSquare<T>`
  - Supports multiple numeric types: `float`, `double`, `int`, `long`, etc.

  == Main classes
  #grid(
    columns: (1fr, 1fr),
    gutter: 1em,
    [
      *Vector<T>*
      - Scalar/dot product
      - Hadamard product
      - Outer product
    ],
    [
      *Matrix2D<T>*
      - Matrix multiplication
      - Transpose
      - Row/column extraction
    ]
  )
]

= Neural network architecture

#slide(title: "Neural network architecture")[
  This is the neural network architecture slide.
]


= Training process

#slide(title: "Training process")[
  - pb of sigmoid fonction : vanishing gradient
  - enregistrer le RDN dans un binaire au lieu d'un txt pour gagner en performance et place
  - normalisation/standardisation des données d'entrée et de sortie
  - differentes fonctions d'activation
  - cost function : MSE because of point correspondance
  - non linear last layer
  
]

= Optimization techniques

== Multithreading
#slide(title: "Multithreading")[

#speaker-note()[
  NN is quiet slow to train --> multi-threading system to speed up the process. \
  
  1. create a thread for each operation that can be parallelized. But the overhead created by the creation of threads is too important because of the large number of threads created compared to the time saved by parallelizing the operation. \
  2. split the operations in a fixed number of threads (depended of the computer threads, basically 4 or 8). Each thread will compute a part of the result vector.
    ]

  === Motivation
    - Speed up training process
    - Efficiently utilize multi-core processors
    - For Matrix x Vector multiplication

  === `std::thread` approaches
    1. For every parallelizable operation, create a thread
    2. Create a fixed number of threads at the beginning
    3. Thread pool
  
  === OpenMP
    - Simple to implement with compiler directives
    - Automatically manages thread creation and workload distribution

  #speaker-note()[  3. thread pool: create a fixed number of threads at the beginning of the program.  This approach reduces the overhead of thread creation and destruction, leading to better performance. We didn't implement beacause of a lack of time. \

  OpenMP expliquer brievement le principe et a quoi ca sert]
#figure(
  image("../fig/perf_multithreading.png", width: 100%),
  caption: [
    Performance comparison between single-threaded and multi-threaded training (with different values of the treshold parameter) // we don't see the caption in touying (here)
  ],
) <perf_multithreading>

]

== Memory allocation
#slide(title: "Memory allocation")[
  TODO
]

= Visualizations

#slide(title: "First visualizations")[
  == `visuFemur.py`
  - Quick OBJ mesh viewer
  - To debug and visualize femur meshes generated by the RDN

  == `compare_femur.py`
  - Compare two femurs meshes (between original and reconstructed femurs for example)

  == `latent_explorer.py`
  - Interactive latent space explorer (sliders)
]

= Live Demo

#focus-slide()[
  Live demo
]

#slide(title: "Conclusion and ameliorations")[
  - RDN with bigger train dataset (test with data augmentation of linear PCA (may not add anything since it's linear))
  - Thread pool

]

#show: appendix

= References

#slide(title: "References")[
  #bibliography("../bibliography.bib", title: none)
]
