/**
 * @file testSyntheticLoad.cpp
 * @brief Test loading synthetic shapes generated by Python
 */

#include <iostream>
#include <filesystem>
#include "../include/femur.hpp"
#include "../include/dataset.hpp"

int main() {
    std::cout << "\n=== Testing Synthetic Data Loading ===" << std::endl;
    
    std::string synth_dir = "../data/synthetic_sanity";
    
    // Check if directory exists
    if (!std::filesystem::exists(synth_dir)) {
        std::cerr << "Synthetic data directory not found: " << synth_dir << std::endl;
        return 1;
    }
    
    // Count OBJ files
    int obj_count = 0;
    for (const auto& entry : std::filesystem::directory_iterator(synth_dir)) {
        if (entry.path().extension() == ".obj") {
            obj_count++;
        }
    }
    std::cout << "Found " << obj_count << " OBJ files in " << synth_dir << std::endl;
    
    // Load first synthetic shape
    for (const auto& entry : std::filesystem::directory_iterator(synth_dir)) {
        if (entry.path().extension() == ".obj") {
            std::string filepath = entry.path().string();
            std::cout << "\nLoading: " << entry.path().filename() << std::endl;
            
            try {
                Femur femur(filepath);
                auto coords = femur.getCoords();
                auto normals = femur.getNormals();
                auto triangles = femur.getTriangles();
                
                std::cout << "  Vertices: " << coords.getSizeRows() << std::endl;
                std::cout << "  Normals: " << normals.getSizeRows() << std::endl;
                std::cout << "  Triangles: " << triangles.getSizeRows() << std::endl;
                
                // Get standardized vector
                auto vec = femur.getCoordsVect<double>(1, true);
                std::cout << "  Vector dim: " << vec.getSize() << std::endl;
                
                // Print first 3 standardized coords
                std::cout << "  First 3 X (std): " << vec(0) << ", " << vec(1) << ", " << vec(2) << std::endl;
                
                std::cout << "  ✓ Load successful!" << std::endl;
                
            } catch (const std::exception& e) {
                std::cerr << "  ✗ Error: " << e.what() << std::endl;
                return 1;
            }
            
            break; // Only test first file
        }
    }
    
    // Test loading multiple as dataset
    std::cout << "\n--- Testing FemurDataset loading ---" << std::endl;
    try {
        FemurDataset<double> dataset(synth_dir, true, 1);
        std::cout << "Loaded " << dataset.size() << " shapes from " << synth_dir << std::endl;
        std::cout << "Dimension: " << dataset.getDimension() << std::endl;
        
        auto matrix = dataset.toMatrix();
        std::cout << "Matrix size: " << matrix.getSizeRows() << " x " << matrix.getSizeCols() << std::endl;
        std::cout << "  ✓ Dataset load successful!" << std::endl;
        
    } catch (const std::exception& e) {
        std::cerr << "  ✗ Dataset error: " << e.what() << std::endl;
        return 1;
    }
    
    std::cout << "\n=== All Tests Passed ===" << std::endl;
    return 0;
}
